AWSTemplateFormatVersion: '2010-09-09'
Description: Simple EC2 Instance

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0f5ee92e2d63afc18  # Amazon Linux (ap-south-1)
      InstanceType: t2.micro
